name: Fumble
description: "Fumble - Find your next project partner"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  fetch_client: ^1.0.2
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.0
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.0
  image_picker: ^1.0.7
  pocketbase: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/fumbleicon.png"
  web:
    generate: true
    image_path: "assets/images/fumbleicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
